name: Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: TheRealQuicT/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: TheRealQuicT
          template: "README.md"

      - uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
